name: infrastructure_flutter
description: The Flutter part of the 'infrastructure' ring of the trad mobile application.
resolution: workspace
publish_to: none

environment:
  sdk: ^3.9.2
  flutter: ^3.35.3

dependencies:
  adapters:
    path: ../adapters
  crosscuttings:
    path: ../crosscuttings
  file_picker: ^10.1.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  loading_indicator: ^3.1.1
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  url_launcher: ^6.3.2

dev_dependencies:
  coverage: ^1.9.2
  dlcov: ^4.2.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  path_provider_platform_interface:  # Use the version defined by path_provider
  plugin_platform_interface:  # Use the version defined by path_provider
  test: ^1.26.0
  very_good_analysis: ^10.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/knowledgebase/index.md
    - assets/knowledgebase/example.md
    - assets/knowledgebase/example.jpg
    - assets/logo.png

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
