name: adapters
description: The 'adapters' ring of the trad mobile application.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  core:
    path: ../core
  crosscuttings:
    path: ../crosscuttings
  intl: ^0.20.0
  meta: ^1.12.0

dev_dependencies:
  coverage: ^1.9.2
  dlcov: ^4.2.1
  file: ^7.0.0
  mocktail: ^1.0.0
  test: ^1.25.0
  very_good_analysis: ^9.0.0
