name: adapters
description: The 'adapters' ring of the trad mobile application.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  core:
    path: ../core
  crosscuttings:
    path: ../crosscuttings

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^5.1.0
