name: infrastructure_vanilla
description: The Dart only part of the 'infrastructure' ring of the trad mobile application.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  adapters:
    path: ../adapters
  crosscuttings:
    path: ../crosscuttings
  path: ^1.9.0
  sqlite3: ^2.4.4

dev_dependencies:
  coverage: ^1.9.2
  dlcov: ^4.2.1
  mocktail: ^1.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
