name: infrastructure_vanilla
description: The Dart only part of the 'infrastructure' ring of the trad mobile application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  crosscuttings:
    path: ../crosscuttings
  adapters:
    path: ../adapters

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
