name: crosscuttings
description: The 'crosscuttings' ring of the trad mobile application.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  get_it: ^7.7.0
  logging: ^1.2.0

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0
