name: crosscuttings
description: The 'crosscuttings' ring of the trad mobile application.
resolution: workspace
publish_to: none

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  get_it: ^8.0.0
  logging: ^1.2.0

dev_dependencies:
  coverage: ^1.9.2
  dlcov: ^4.2.1
  test: ^1.25.0
  very_good_analysis: ^9.0.0
