name: mobileapp

on: [push, pull_request]

jobs:
  check-style:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./mobileapp

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub global activate melos

      - name: Check code style
        run: melos run format

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      #- name: Analyze project source
      #  run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      #- name: Run tests
      #  run: dart test
