name: mobileapp

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: ["linux", "android"]

    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: ./mobileapp

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.x

      - name: Setup environment
        run: |
             echo "--- Install build requirements"
             sudo apt install -y ninja-build libgtk-3-dev
             echo "--- Configure Flutter"
             flutter config --no-analytics
             flutter config --no-cli-animations
             echo "--- Install Melos"
             dart pub global activate melos
             echo "--- Install requirements"
             melos bootstrap

      - name: Build app in release mode
        run: melos run build.${{ matrix.platform }}
        
      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: trad-${{ matrix.platform }}
          path: mobileapp/artifacts/*
          retention-days: 1


  check-style:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: ./mobileapp

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install Melos
        run: dart pub global activate melos

      - name: Check code style
        run: melos run format

  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: ./mobileapp

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.x

      - name: Setup environment
        run: |
             echo "--- Configure Flutter"
             flutter config --no-analytics
             flutter config --no-cli-animations
             echo "--- Install Melos"
             dart pub global activate melos
             echo "--- Install requirements"
             melos bootstrap

      - name: Run the Dart linter
        run: melos run analyze
        
  test:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: ./mobileapp

    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.x

      - name: Setup environment
        run: |
             echo "--- Configure Flutter"
             flutter config --no-analytics
             flutter config --no-cli-animations
             echo "--- Install Melos"
             dart pub global activate melos
             echo "--- Install requirements"
             sudo apt install -y libsqlite3-dev
             melos bootstrap
             echo "--- Install coverage tools"
             sudo apt install -y lcov

      - name: Run all tests
        run: melos run test

      - name: Generate code coverage report
        run: melos run coverage

      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: trad-coverage-report
          path: mobileapp/coverage/report/*
          retention-days: 1
          
      - name: Publish HTML coverage report
        if: github.ref == 'refs/heads/main'
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.REPORT_FTP_HOST }}
          user: ${{ secrets.REPORT_FTP_USER }}
          password: ${{ secrets.REPORT_FTP_PW }}
          localDir: "mobileapp/coverage/report/"
          remoteDir: ${{ env.CI_REF_NAME }}
          options: "--delete"
