name: mobileapp

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: ["linux", "android"]

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./mobileapp

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.x

      - name: Setup environment
        run: |
             echo "--- Install build requirements"
             sudo apt install -y ninja-build libgtk-3-dev
             echo "--- Configure Flutter"
             flutter config --no-analytics
             flutter config --no-cli-animations
             echo "--- Install Melos"
             dart pub global activate melos

      - name: Build app in release mode
        run: melos run build.${{ matrix.platform }}
        
      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: trad-${{ matrix.platform }}
          path: mobileapp/artifacts/*
          retention-days: 1


  check-style:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./mobileapp

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install Melos
        run: dart pub global activate melos

      - name: Check code style
        run: melos run format

        
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./mobileapp

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.x

      - name: Setup environment
        run: |
             echo "--- Configure Flutter"
             flutter config --no-analytics
             flutter config --no-cli-animations
             echo "--- Install Melos"
             dart pub global activate melos

      - name: Run all tests
        run: melos run test

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      #- name: Analyze project source
      #  run: dart analyze
